Repository LGugs3/Surprise-Delivery-App, pull requests merged in 2025-03, with the labels that each got.

#62 Create Issue and PR Templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#64 Fixed sign up error messages
  Surprise_Delivery_App/lib/pages/signup_page.dart
  Surprise_Delivery_App/macos/Flutter/GeneratedPluginRegistrant.swift
  Surprise_Delivery_App/pubspec.lock
  Surprise_Delivery_App/windows/flutter/generated_plugin_registrant.cc
  Surprise_Delivery_App/windows/flutter/generated_plugins.cmake
Labels: bug

#68 Order form
  .gitignore
  Surprise_Delivery_App/lib/pages/home_page.dart
  Surprise_Delivery_App/lib/pages/order_form.dart
  Surprise_Delivery_App/lib/pages/preference_page.dart
  Surprise_Delivery_App/lib/pages/settings_page.dart
  Surprise_Delivery_App/lib/pages/signup_page.dart
  Surprise_Delivery_App/macos/Flutter/GeneratedPluginRegistrant.swift
Labels: Project Assignment

#65 Made some QOL updates and fixed some minor inconsistencies.
  Surprise_Delivery_App/.gitignore
  Surprise_Delivery_App/lib/pages/preference_page.dart
  Surprise_Delivery_App/lib/pages/settings_page.dart
  Surprise_Delivery_App/lib/pages/signin_page.dart
  Surprise_Delivery_App/lib/reusable_widgets/reusable_widget.dart
  Surprise_Delivery_App/pubspec.lock
Labels: Project Assignment

#76 Test/unit test creation
  .github/workflows/codeql.yml
  .github/workflows/findEnv.yml
  .github/workflows/findSecretKeys.yml
  .github/workflows/flutterTests.yml
  .idea/caches/deviceStreaming.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  Surprise_Delivery_App/lib/pages/base_map.dart
  Surprise_Delivery_App/lib/pages/home_page.dart
  Surprise_Delivery_App/lib/pages/order_form.dart
  Surprise_Delivery_App/lib/pages/preference_page.dart
  Surprise_Delivery_App/lib/pages/second_orderformpage.dart
  Surprise_Delivery_App/lib/pages/settings_page.dart
  Surprise_Delivery_App/lib/pages/signin_page.dart
  Surprise_Delivery_App/lib/reusable_widgets/reusable_widget.dart
  Surprise_Delivery_App/pubspec.lock
  Surprise_Delivery_App/pubspec.yaml
  Surprise_Delivery_App/test/finder_widgets.dart
  Surprise_Delivery_App/test/navigation.dart
  Surprise_Delivery_App/test/standardTest.dart
  Surprise_Delivery_App/test/widget_test.dart
Labels: Project Assignment
